name: CI

# 触发 workflow 的事件，当有新push或者pr时执行
on:
  push:
    branches: [ master ]
# 一个workflow由执行的一项或多项job
jobs:
  # 一个job任务，任务名为build
  build:
    runs-on: ubuntu-latest
	# steps是每个Job的运行步骤，可以包含一个或多个步骤
    steps:
    - uses: actions/checkout@v2
	# action命令，打印一行日志
    - name: Run a one-line script
      run: echo Hello, world!
	# action命令，打印多行日志
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
